### ISSUE TITLE
YouTube录播部分已经损坏

### ISSUE THREAD

**Issue by wudifeixue** [lovezzzxxx/liverecord#1]
详细问题 https://github.com/printempw/live-stream-recorder/issues/9

**Comment by lovezzzxxx** [comment]
streamlink对于youtube现在只能支持watch?v=类型的链接（检测方法改为通过curl检测页面islive判断直播状态，请手动设置录制方法参数为`youtubecurl`；录制方法改为直接提交watch?v=类型的链接给streamlink，已在脚本内修改）和非60fps的视频录制（请手动设置清晰度参数为`1080p,720p,480p,360p,worst`）。

即此脚本录制youtube暂时修改为`record.sh youtubecurl 频道号 1080p,720p,480p,360p,worst`

这样修改暂时损失了对60fps视频的支持，进一步的修复可以等youtube更新稳定下来后再进行。

**Comment by lovezzzxxx** [comment]
直接使用curl获取解析网页方式相对比较可靠，所以将其作为默认的检测方式。故目前第一个参数中与youtube相关的可用参数为youtube与youtubeffmpeg，注意如果之前将第一个参数设为youtubecurl与youtubecurlffmpeg则需要再修改回来。

streamlink依然没有修复对youtube 60fps以及1080p以上流（不含1080p）的支持，另外这些流为muxed-stream故无法直接通过streamlink获取直播流链接并交由ffmpeg录制。故目前youtube的录制需要限制清晰度为1080p即一下的非60fps流，推荐使用`1080p,720p,480p,360p,worst`参数。
