### ISSUE TITLE
b站的录播会莫名其妙的分成好几段

### ISSUE THREAD

**Issue by clhaaaa** [lovezzzxxx/liverecord#12]
loop模式下的录制，有时候是会录下来完整的，有时候会录成几段大小不等的视频，这和网络情况有关吗？

**Comment by lovezzzxxx** [comment]
b站的海外直播确实不太稳定，如果经常断流多半是网络波动导致的，虽然可能作用不大，不过可以试试使用不同的下载方式，或者修改一下超时时间看看（当然最直接的办法还是改善一下网络

**Comment by clhaaaa** [comment]
> b站的海外直播确实不太稳定，如果经常断流多半是网络波动导致的，虽然可能作用不大，不过可以试试使用不同的下载方式，或者修改一下超时时间看看（当然最直接的办法还是改善一下网络

明白了……
