### ISSUE TITLE
大佬，纯小白想问下在VPS上搭建的教程

### ISSUE THREAD

**Issue by HoshifuriKaoru** [lovezzzxxx/liverecord#15]
自己D了一个小众TC，目前有个VPS，想搭一个自动录播机自动录制并上传云盘。
看到的大佬的自动录播的帖子，想问下食用教程。
第一步如何安装到VPS上？包括环境依赖
然后我想录制完成后自动上传百度云参数设置是不是只用输入：
./record.sh twitcast  "TC台名字"   worst once 30 "record_video/TC主名字" rclone:vps:baidupan3
record_video/TC主名字和百度盘这里我有点没明白怎么设置.
twitcast|twitcastffmpeg|twitcastpy这仨哪个稍微好点？
然后如果上传云盘失败了如何检查、下载和删除VPS本地未删除的视频文件？

**Comment by lovezzzxxx** [comment]
安装的话可以先查一下linux服务器的连接方法和基本操作，然后按照那些依赖的github说明安装环境，最后把record.sh下载到服务器并给予可执行权限就好了(要用twitcastpy的话把record_twitcast.py文件放到record.sh相同路径并给予可执行权限)
录制tc并上传百度云的话`record.sh twitcastpy "TC台名字" best loop 30,5 "任意保存路径" baidupan3`；目前个人感觉twitcastpy好像是最稳定的，不过也可以各种方法都录一下试试；如果上传失败了并且没有添加在baidupan3后面添加del参数的话录像会保留在上面设置的"任意保存路径"中，然后手动下载或者上传网盘就随意了

**Comment by lovezzzxxx** [comment]
简单在文档里介绍了一下环境依赖的安装方法，不过只录制tc台的话其实只需要配置好record_twitcast.py然后使用twitcastpy参数录制就行了，如果需要上传网盘的话再另外配置相应的网盘上传程序即可

**Comment by lovezzzxxx** [comment]
更新了一键脚本，这样配置录播环境应该会更加方便了
