### ISSUE TITLE
运行提示metadata livestatus=0

### ISSUE THREAD

**Issue by Zynismus16** [lovezzzxxx/liverecord#16]
感谢大大的无私奉献
当我运行record.sh时提示
`[2020-02-16 20:05:40] metadata https://www.youtube.com/channel/UCKVlixycWmapnGQ_wht4cHQ/live
[2020-02-16 20:05:40] metadata islive_youtube=0
[2020-02-16 20:05:40] metadata livestatus=0`
我的运行命令是
`sh record.sh youtube "UCKVlixycWmapnGQ_wht4cHQ" "File/"`
请问是怎么了

**Comment by lovezzzxxx** [comment]
livestatus是"连续检测到开播的次数"，因为有时候会出现检测到开播但实际并未开播的情况，所以增加了一个需要连续检测到开播才会开始录制的选项，可以在第五个设置检测间隔的参数中进行设置，比如设置为10,10,3的话就会在连续检测到开播三次之后livestatus=3时才开始录制

islive_youtube是为了针对youtube的开播和下播使用不同的检测方法，因为不同的检测方法对于开播和下播有不同的延迟，在未直播时islive_youtube=0则会使用开播延迟更低的检测方法，在直播时islive_youtube>0则会使用下播延迟更低的检测方法

**Comment by lovezzzxxx** [comment]
另外指定录制频道和指定录像存放路径之间的几个参数不能省，要补齐才能正常使用😂（主要是懒得改了）
