### ISSUE TITLE
有关于录制列表的问题

### ISSUE THREAD

**Issue by namemina** [lovezzzxxx/liverecord#18]
我是个纯小白，个人租了个vps服务器想要进行录制，但是在录入列表中我因为不知道这个录入的指令是否成功，请问该使用什么指令来查看当前已经录入的列表呢?

**Comment by lovezzzxxx** [comment]
一般来说会使用`nohup ... &`的方式让脚本在后台运行，如果是这样的话使用`ps aux`应该就能看到所有的进程，使用`ps aux | grep "record.sh"`的话应该就能筛选出脚本进程了（不过脚本正在录制时产生的录制进程可能看不到，比如streamlink或者livedl等等）
