### ISSUE TITLE
关于record.sh脚本

### ISSUE THREAD

**Issue by asagokagami** [lovezzzxxx/liverecord#19]
![2${C( ~%HJ@5 LLXDOHD 31](https://user-images.githubusercontent.com/61354838/75094347-8e2a1280-55cd-11ea-9183-07706f9e7ea1.png)
2020.02.22 Overidea直播的录制是一直重复这样的循环，请问这是ip被ban了吗...其他所有的youtube直播录制都是这种情况，isLive检测先是0，然后是3， 本地没有ts文件

**Comment by lovezzzxxx** [comment]
如果使用youtube参数录制youtube直播的话实际是调用streamlink进行录制的，可以直接找一个youtube直播试着用streamlink录制一下，或者用curl获取一个youtube的页面，如果不能正常录制或者获取的话应该就是ip被youtube封了，一般来说可能要一周左右才能解封。这种时候可以试试更换其他的ip（如果有ipv6的话可以试着更换ipv4）

**Comment by asagokagami** [comment]
感觉还需要时间测试，昨晚的录播都炸了然而今天又看到了正常上传的今天直播的录播......太神秘了
