### ISSUE TITLE
无法拉取streamlink支持网站

### ISSUE THREAD

**Issue by Zynismus16** [lovezzzxxx/liverecord#20]
大大您好,前段时间,我有反馈拉取youtube直播提示
metadata livestatus=0
您给我的解决方法是设置循环检测时间和次数
我的实际使用目的是拉取iss国际空间站在ustream.tv的直播
实际情况和youtube是一样的,当我按照您给我的解决方案修改后还是反馈
`[2020-02-25 06:12:09] metadata https://www.ustream.tv/channel/iss-hdev-payload
[2020-02-25 06:12:12] metadata livestatus=0
`
我的运行命令是
`bash record.sh streamlink "https://www.ustream.tv/channel/iss-hdev-payload" best 20 10,10,1 "ISS"`
我也尝试过把检测次数更改为零
反馈提示
`[2020-02-25 06:16:52] metadata https://www.ustream.tv/channel/iss-hdev-payload
[2020-02-25 06:16:55] metadata livestatus=0
`
这种情况是不是无法检测这个链接的开播情况,还是说无法拉取直播文件
望大大,排查下
如有打扰,请见谅.谢谢

**Comment by Zynismus16** [comment]
`[2020-02-25 06:13:04] record start pid=27228 looptime=20 url=error: The stream specified cannot be translated to a URL`
这个也是把检测次数改为0反馈的

**Comment by lovezzzxxx** [comment]
哦这是因为脚本是通过streamlink能否获取直播流链接来判断能否录制的，但这个直播似乎不能直接获取到这个链接。
我对这种情况加了新的判断条件，现在更新一下脚本应该就能正常录制了。
