### ISSUE TITLE
关于上传问题

### ISSUE THREAD

**Issue by kokoro223** [lovezzzxxx/liverecord#21]
你好，本人是纯小白，按照教程进行配置了，然后键入nohup record/record.sh youtubeffmpeg "UCa9Y57gfeY0Zro_noHRVrnw" best once 30 "record_demo"rclone:vps:baidupan3 意思应该就是后台运行使用ffmpeg录制UCa9Y57gfeY0Zro_noHRVrnw频道最高清晰度，在检测到直播并进行一次录制后终止，间隔30秒检测，保存录像路径是record_demo，并上传到rclone登陆的名为vps的网盘以及百度盘，录制是成功的但是并没有上传，所以关于这个上传的问题能否再详细的讲解一下，实在是不好意思。

**Comment by zhz1237ok** [comment]
间隔那边的参数改了，具体看项目主页下面的参数

nohup record/record.sh youtubeffmpeg UCa9Y57gfeY0Zro_noHRVrnw best once 30,10,1 "record_demo" baidupan3 &

循环检测间隔秒数,最短录制间隔秒数,录制开始所需连续检测开播次数

建议once改成loop，不然就录一次脚本就停止了

**Comment by kokoro223** [comment]
我需要的就是录制单次后停止，但是并没自动上传到我我指定的网盘，之前偶然一次在开播的时候键入了指令录制了各个分段并成功上传，就很奇怪

**Comment by lovezzzxxx** [comment]
如果运行完之后本地还留有录像的话可能是上传失败导致的，如果上传失败的话会在录像路径下产生一个errorlog文件，里面会记录错误信息

另外"record_demo"后面似乎漏了空格？

其实once我个人测试的不是很多，因为这和直接用streamlink录制差别不大😂
