### ISSUE TITLE
ubuntu1804环境下的问题

### ISSUE THREAD

**Issue by KUNproject** [lovezzzxxx/liverecord#22]
（本人纯小白，如果问了很白痴的问题，还请多多包涵）

1. 输入`record/record.sh youtube "UC6oDys1BGgBsIC3WhG1BovQ"`，尽管该主播正在直播，始终提示islive_youtube=0（已测试过youtube的多个主播，均如此）

2. 无论是bilibili、twitcast、twitcastpy，以默认参数执行脚本，并检测到正在直播后，均提示`record_video/other/XXXXXX.flv file not exist remove log`，无法录像

3. 输入 `record/record.sh twitcastffmpeg "usam0m0nana"  `后，显示
```
[2020-03-31 20:13:51] metadata https://twitcasting.tv/usam0m0nana
[2020-03-31 20:13:51] metadata livestatus=1
[2020-03-31 20:13:54] record start pid=75 looptime=loop url=https://202-239-41-100.twitcasting.tv/mpegts/602902897-8cbc922a1b92e962/ts-source.m3u8
```
控制台便不再更新，也找不到录像文件（在`C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1804.2020.5.0_x64__79rhkp1fndgsc`目录，即ubuntu安装目录下找不到录像文件）

**Comment by zhz1237ok** [comment]
WIN10的子系统？那你截图给看看路径下的文件夹啊，WIN10子系统能成功按上这一系列依赖包吗

**Comment by umauc** [comment]
同样的问题,Ubuntu18.04 LTS

**Comment by lovezzzxxx** [comment]
windows子系统我也没有测试过😂可能只有一步步排查了
1.检测youtube主要用到了curl，试试curl "youtube直播链接"看看能不能正确获取页面？
2.bilibili用的是you-get下载，twitcast用的是livedl下载（一键脚本会安装到livedl/livedl），twitcastpy用的是record_twitcast.py（一键脚本会安装到record/record_twitcast.py）。试试直接运行you-get "bilibili直播链接"，livedl/livedl "twitcast直播链接"看看能不能正常下载？
