### ISSUE TITLE
请求添加哔哩哔哩录制之后flv转封装为mp4

### ISSUE THREAD

**Issue by Theergold** [lovezzzxxx/liverecord#24]
哔哩哔哩使用you-get下载的直播流是flv格式的,但是flv格式的时间码是有问题的,并且flv格式无法导入大多数视频软件.
所以可否添加一个
````ffmpeg -i input.flv -vcodec copy -acodec copy output.mp4````
的命令把flv转封装成mp4格式,这样比较方便后续处理

**Comment by railannad** [comment]
你好，尽管我不是作者，我来分享一个"可能"可行的办法：
你可以直接魔改代码，参考record.sh的402行，这一行是上传百度网盘的命令
`BAIDUPAN_FILE_ERRFLAG=$(BaiduPCS-Go upload "${DIR_LOCAL}/${FNAME}" "${DIR_BAIDUPAN}")`
其中"$FNAME"是录制程序输出的文件名，$DIR_LOCAL是本地目录 

对于你这条命令，你可以在399行的then之后（识别到备份网盘为百度盘，如果是其他网盘请自行替换）添加`ffmpeg -i ${DIR_LOCAL}/${FNAME}.flv -vcodec copy -acodec copy ${DIR_LOCAL}/${FNAME}.mp4;`   

但是有一个缺点，有点麻烦：
$FANME本身就包含了.FLV后缀，转换完成后文件名会变成 XXX.FLV.MP4，需要用mv命令重命名成 XXX.FLV 之后上传命令才能识别此文件，因此下载后需要恢复后缀为MP4。 

题外话：这个方法我没有测试过，不知道是否可行，灵感是从创建压缩包并设置密码得来的，可行，缺点是下载完之后需要改后缀为zip。我在用这个程序监控nico上做ASMR的小姐姐，上个月百度对几个司机的号进行永封，我研究了一晚上才搞出这个法子。

**Comment by SekiBetu** [comment]
推荐软甲XMedia Recode，一分钟拆flv换mp4一份2G的flv
可批量进行

**Comment by Theergold** [comment]
> 
> 
> 你好，尽管我不是作者，我来分享一个"可能"可行的办法：
> 你可以直接魔改代码，参考record.sh的402行，这一行是上传百度网盘的命令
> `BAIDUPAN_FILE_ERRFLAG=$(BaiduPCS-Go upload "${DIR_LOCAL}/${FNAME}" "${DIR_BAIDUPAN}")`
> 其中"$FNAME"是录制程序输出的文件名，$DIR_LOCAL是本地目录
> 
> 对于你这条命令，你可以在399行的then之后（识别到备份网盘为百度盘，如果是其他网盘请自行替换）添加`ffmpeg -i ${DIR_LOCAL}/${FNAME}.flv -vcodec copy -acodec copy ${DIR_LOCAL}/${FNAME}.mp4;`
> 
> 但是有一个缺点，有点麻烦：
> $FANME本身就包含了.FLV后缀，转换完成后文件名会变成 XXX.FLV.MP4，需要用mv命令重命名成 XXX.FLV 之后上传命令才能识别此文件，因此下载后需要恢复后缀为MP4。
> 
> 题外话：这个方法我没有测试过，不知道是否可行，灵感是从创建压缩包并设置密码得来的，可行，缺点是下载完之后需要改后缀为zip。我在用这个程序监控nico上做ASMR的小姐姐，上个月百度对几个司机的号进行永封，我研究了一晚上才搞出这个法子。

好的,我试一试,非常感谢

**Comment by railannad** [comment]
> > 你好，尽管我不是作者，我来分享一个"可能"可行的办法：
> > 你可以直接魔改代码，参考record.sh的402行，这一行是上传百度网盘的命令
> > `BAIDUPAN_FILE_ERRFLAG=$(BaiduPCS-Go upload "${DIR_LOCAL}/${FNAME}" "${DIR_BAIDUPAN}")`
> > 其中"$FNAME"是录制程序输出的文件名，$DIR_LOCAL是本地目录
> > 对于你这条命令，你可以在399行的then之后（识别到备份网盘为百度盘，如果是其他网盘请自行替换）添加`ffmpeg -i ${DIR_LOCAL}/${FNAME}.flv -vcodec copy -acodec copy ${DIR_LOCAL}/${FNAME}.mp4;`
> > 但是有一个缺点，有点麻烦：
> > $FANME本身就包含了.FLV后缀，转换完成后文件名会变成 XXX.FLV.MP4，需要用mv命令重命名成 XXX.FLV 之后上传命令才能识别此文件，因此下载后需要恢复后缀为MP4。
> > 题外话：这个方法我没有测试过，不知道是否可行，灵感是从创建压缩包并设置密码得来的，可行，缺点是下载完之后需要改后缀为zip。我在用这个程序监控nico上做ASMR的小姐姐，上个月百度对几个司机的号进行永封，我研究了一晚上才搞出这个法子。
> 
> 好的,我试一试,非常感谢

之前发的命令有问题，把-i后面的.flv后缀删掉就行了，因为$FNAME已经包含了flv后缀（原谅我家里停电只能用手机码字，不能复制原命令）

**Comment by lovezzzxxx** [comment]
如果需要自动转码的话确实像这样直接修改脚本可以了，或者下载到本地之后再转码应该也行？
因为脚本本身还是着重于录制和上传的功能，如果非必要就尽量不添加功能了😂（主要是我太菜了，加点功能可能得多一堆问题）
