### ISSUE TITLE
baidupcs-go被删除

### ISSUE THREAD

**Issue by kokoro223** [lovezzzxxx/liverecord#25]

**Comment by SekiBetu** [comment]
https://github.com/SekiBetu/BaiduPCS-Go
我fork的最后的版本，先用着，然后转移到别的网盘

**Comment by SekiBetu** [comment]
https://github.com/houtianze/bypy
@lovezzzxxx 看看这个

**Comment by lovezzzxxx** [comment]
啊这，暂时来说有这几个办法吧：
1.BaiduPCS-Go使用的api暂时还没改，所以已经安装好的应该可以再用一段时间。如果需要安装的话github上也还有几份克隆的源码，下载到本地然后go build编译就行了。
2.改用bypy，看了下bypy调用的方式基本和BaiduPCS-Go相同，修改一下脚本上传命令和上传成功与否的判断应该就能用了。如果急用的话可以先自行修改，由于没有测试它的稳定性所以正式添加到脚本里可能还要一点时间（咕咕警告😂
3.停用百度

**Comment by kokoro223** [comment]
了解
