### ISSUE TITLE
17的直播是否录制不了?

### ISSUE THREAD

**Issue by cyasgg** [lovezzzxxx/liverecord#26]
17的直播是否录制不了? 一直显示metadata livestatus=0
或者我能问你怎样录制17的直播吗？

**Comment by lovezzzxxx** [comment]
17live确实换了api了，最新的版本应该可以正常录制了

**Comment by cyasgg** [comment]
那出现 403 Forbidden (access denied) 要怎样?
[https @ 0x560634d79840] HTTP error 403 Forbidden
https://wansu-global-pull-rtmp.17app.co/vod/9bb3976b-c050-4396-9184-23ce86e8694e.flv: Server returned 403 Forbidden (access denied)

**Comment by lovezzzxxx** [comment]
好像需要加个请求头，又更新了一下
