### ISSUE TITLE
chaturbate站录得视频卡顿

### ISSUE THREAD

**Issue by opencasting** [lovezzzxxx/liverecord#27]
请教大佬，全部配置好后，录制没问题，就是下载录像后发现所有录像的视频均两三秒画面卡顿一下，声音是流程的，感觉是拼接的时候出了问题，请大佬解惑，命令是
nohup ./record.sh chaturbate "krissone" best loop 20,5,2 "record_video/krissone" rclone:liverecord:onedrive3 > krissone.log 2>&1 &
部分log是
skipping 2 segments ahead, expired from playlists
[https @ 0x12d6d00] No trailing CRLF found in HTTP header.
frame=31770 fps= 25 q=-1.0 size=  310058kB time=00:21:18.07 bitrate=1987.4kbits/s    
frame=31799 fps= 25 q=-1.0 size=  310285kB time=00:21:18.58 bitrate=1988.0kbits/s    
[tls @ 0x167b1a0] The TLS connection was non-properly terminated.
skipping 1 segments ahead, expired from playlists
[https @ 0x12d6d00] No trailing CRLF found in HTTP header.
frame=31860 fps= 25 q=-1.0 size=  310764kB time=00:21:21.06 bitrate=1987.2kbits/s    
frame=31889 fps= 25 q=-1.0 size=  310995kB time=00:21:21.57 bitrate=1987.9kbits/s    
[tls @ 0x167b1a0] The TLS connection was non-properly terminated.
skipping 2 segments ahead, expired from playlists
[https @ 0x12d6d00] No trailing CRLF found in HTTP header.
frame=31949 fps= 25 q=-1.0 size=  311459kB time=00:21:25.54 bitrate=1984.7kbits/s    
frame=31960 fps= 25 q=-1.0 size=  311537kB time=00:21:25.73 bitrate=1984.9kbits/s    
frame=32010 fps= 25 q=-1.0 size=  311933kB time=00:21:26.57 bitrate=1986.2kbits/s    
[tls @ 0x167b1a0] The TLS connection was non-properly terminated.
[https @ 0x12d6d00] No trailing CRLF found in HTTP header.
frame=32039 fps= 25 q=-1.0 size=  312162kB time=00:21:27.08 bitrate=1986.8kbits/s    
frame=32051 fps= 25 q=-1.0 size=  312253kB time=00:21:27.24 bitrate=1987.2kbits/s    
frame=32101 fps= 25 q=-1.0 size=  312682kB time=00:21:28.08 bitrate=1988.6kbits/s    
[tls @ 0x19287a0] The TLS connection was non-properly terminated.
skipping 2 segments ahead, expired from playlists
[https @ 0x12d6d00] No trailing CRLF found in HTTP header.
frame=32131 fps= 25 q=-1.0 size=  312862kB time=00:21:31.54 bitrate=1984.4kbits/s    
frame=32156 fps= 25 q=-1.0 size=  313072kB time=00:21:31.98 bitrate=1985.1kbits/s    
[tls @ 0x19f5ac0] The TLS connection was non-properly terminated.
[https @ 0x1a5b2a0] HTTP error 403 Forbidden
[hls,applehttp @ 0x12cf460] Failed to reload playlist 0
[https @ 0x1a5b2a0] HTTP error 403 Forbidden
[hls,applehttp @ 0x12cf460] Failed to reload playlist 0
frame=32220 fps= 25 q=-1.0 size=  313569kB time=00:21:33.02 bitrate=1986.6kbits/s    
frame=32220 fps= 25 q=-1.0 Lsize=  313578kB time=00:21:33.02 bitrate=1986.7kbits/s    
video:280752kB audio:6290kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 9.244741%

**Comment by SekiBetu** [comment]
网络问题

**Comment by opencasting** [comment]
> 网络问题

在本地ubuntu也试了下还是不行，后来发现是自带源的ffmpeg版本太低了，用ppa安装4.0版本以上的就可以了

**Comment by lovezzzxxx** [comment]
那更新ffmpeg之后应该可以正常录了吧？

**Comment by huhansome** [comment]
阿里云服务器，限时秒杀价低至102/年
http://weibo.ws/zZNbxG
阿里云企业级服务器1折限时特惠
http://weibo.ws/SIyDRE
阿里云建站 速成美站 - 千套模板，价格低至500元
http://weibo.ws/yVQAYW
