### ISSUE TITLE
[feature request] fm.missevan.com

### ISSUE THREAD

**Issue by taseikyo** [lovezzzxxx/liverecord#29]
能把猫耳加上嘛？搜了一下 GitHub 上貌似没有相关的项目
猫耳的直播间是 https://fm.missevan.com/live/xxxx，看看能否实现，感谢😂

**Comment by lovezzzxxx** [comment]
啊这 我最近可能没有很多时间添加新功能，刚刚简单的加了一下猫耳的录制功能但是还没有完整的测试过，如果有bug的话可以在这里反馈给我

**Comment by taseikyo** [comment]
感谢 我试一下看行不行😁
