### ISSUE TITLE
bili录制相关已经损坏

### ISSUE THREAD

**Issue by LGKKY** [lovezzzxxx/liverecord#3]
大概是从9/4日发现的问题 无限重试 怀疑是streamlink获取不到直播地址的问题（

**Comment by lovezzzxxx** [comment]
之前bilibili限制了ffmpeg的请求头，但目前似乎已经恢复。
目前bilibili似乎对获取之哦媒体流链接的ip作了限制，故添加代理功能以备用。

更加可靠的方法可能需要等bilibili稳定后进行。
