### ISSUE TITLE
Youtube能否支援登入錄影呢?

### ISSUE THREAD

**Issue by jay860213** [lovezzzxxx/liverecord#30]
Youtube能否支援登入錄影呢?
雖然不知道登入後會不會改善，沒登錄發現放久了會被youtube AI給ban掉
(Youtube 429 Client Error: Too Many Request)

**Comment by railannad** [comment]
想知道你用了什么命令导致Too Many Request。（我猜是you-get）

youtube-dl 有一个关于Too Many Requset的错误，看 [这里](https://github.com/ytdl-org/youtube-dl#faq)  
原因是滥用导致IP被ban。正好我前天也遇到这个问题，我的解决办法搭一个V2ray代理用Windows开浏览器搞定这个验证码，然后用--cookies参数把cookie传递给youtube-dl。
但是我也不知道you-get能不能传递cookie。  所以针对你这个问题，还是要搞明白你用的是什么命令，然后推断出调用了什么程序，再看看能不能解决或者用别的脚本去代替

**Comment by lovezzzxxx** [comment]
其实要修改录制方法的话直接在脚本里的youtube-dl那一行添加参数就可以了，不过ip被ban很可能不是由于录制而是检测过于频繁导致的，把检测间隔调节到三分钟以上可能会有帮助
