### ISSUE TITLE
youtube无法检测到视频流

### ISSUE THREAD

**Issue by tio-plato** [lovezzzxxx/liverecord#36]
已开播的直播间无法检测到视频流，看了下streamlink那边的issue也有提同样的问题，但是好像已经被标记为已解决了

**Comment by SekiBetu** [comment]
测试streamlink可以录制YouTube，要不你更新下streamlink看看，或者看看网络状况良好吗

**Comment by tio-plato** [comment]
今天刚使用一键脚本安装的，但是我常识apt install streamlink之后发现没有安装streamlink。不过通过apt安装streamlink之后，再次测试报错与之前没区别。
```
[2020-12-20 07:28:41] record start: PID=7329, PART_URL=UC1opHUrw8rvnsadT-iGp7Cg, STREAM_ID=JgT5vhDB7W8, STREAM_URL=error: Could not find a video on this page, FNAME=youtube_UC1opHUrw8rvnsadT-iGp7Cg_20201220_072839_JgT5vhDB7W8.ts
```
能获取到streamId但是无法获取streamUrl
机器网络环境正常，使用YouTube-dl+FFmpeg能正常录制直播源

**Comment by lovezzzxxx** [comment]
可以试试直接运行streamlink看看能不能正常获取链接`streamlink --stream-url "url" best`

另外确认streamlink版本可以直接运行`streamlink -v`，apt包更新有时候会晚于pip源，两者同时存在的话似乎是优先使用apt安装的版本

**Comment by tio-plato** [comment]
我直接调用streamlink确认了一下，应该就是streamlink的无法获取URL格式为```"https://www.youtube.com/channel/<channelID>/live"```的页面视频连接的bug，对于这种格式的URL Streamlink会返回```error: Could not find a video on this page```

对于```"https://www.youtube.com/watch?v=<videoID>"```这种格式URL能正常获取视频链接。
目前使用的streamlink版本是stable最新版1.7，可能streamlink那边把这个修复提交到每夜版但是还没合并到stable版本。
不过据说streamlink在搞2.0，不知道啥时候能推新的版本了。

**Comment by SekiBetu** [comment]
> 我直接调用streamlink确认了一下，应该就是streamlink的无法获取URL格式为`"https://www.youtube.com/channel/<channelID>/live"`的页面视频连接的bug，对于这种格式的URL Streamlink会返回`error: Could not find a video on this page`
> 
> 对于`"https://www.youtube.com/watch?v=<videoID>"`这种格式URL能正常获取视频链接。
> 目前使用的streamlink版本是stable最新版1.7，可能streamlink那边把这个修复提交到每夜版但是还没合并到stable版本。
> 不过据说streamlink在搞2.0，不知道啥时候能推新的版本了。

用 https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/youtube.py 替换 /usr/lib/python3/dist-packages/streamlink/plugins 目录中的 youtube.py 即可

**Comment by tio-plato** [comment]
替换后能够获取链接，可以正常使用，感谢二位耐心帮助
