### ISSUE TITLE
install.sh脚本中卸载go的位置不正确

### ISSUE THREAD

**Issue by NagisaCo** [lovezzzxxx/liverecord#40]
代码14行中
```
sudo rm -rf /usr/local/go #如果有已经安装的go环境，先卸载，新老版本会有冲突，如不希望可以注释掉
```
在我的ubuntu上默认go的位置在 
> /usr/bin/go

默认的版本是

> go version go1.10.4 linux/amd64

会导致编译livedl时出现以下错误
> \# github.com/gin-gonic/gin
../go/src/github.com/gin-gonic/gin/context.go:80:11: undefined: http.SameSite

**Comment by lovezzzxxx** [comment]
其实清理旧版go并非必要的步骤。现在livedl更新之后应该可以自动获取依赖的库了，可以直接再运行脚本试试？

**Comment by SekiBetu** [comment]
我是根据golang官网的卸载指导加了这一句，各大发行版可能路径不同，手动删一下就好了
https://golang.org/doc/manage-install#uninstalling

**Comment by SekiBetu** [comment]
不过，楼主这个问题似乎是golang版本太老了
SameSite 至少需要 golang 1.11 版本以上才支持

**Comment by lovezzzxxx** [comment]
新的更新换用相对的GOROOT了，不过如果streamlink对nico与twitcast支持稳定的话也有直接放弃livedl的打算

**Comment by NagisaCo** [comment]
> 新的更新换用相对的GOROOT了，不过如果streamlink对nico与twitcast支持稳定的话也有直接放弃livedl的打算

好的，我关闭issue了
