### ISSUE TITLE
会突然停掉检测

### ISSUE THREAD

**Issue by 9ikj** [lovezzzxxx/liverecord#50]
![image](https://user-images.githubusercontent.com/10474114/116795998-a075d980-ab0b-11eb-8ab0-fa74337e44be.png)
今天早上起来登录vps看到25号停止检测了

**Comment by lovezzzxxx** [comment]
唔，好像也有人反映了类似的问题，log也是突然断掉了没找到具体原因。。。
不知道start_azara.sh启动脚本里面的内容是怎样的呢？

**Comment by 9ikj** [comment]
![image](https://user-images.githubusercontent.com/10474114/119688030-3b977000-be7a-11eb-9fa0-3ad88692a042.png)
我在这边加了一个重试1次
![image](https://user-images.githubusercontent.com/10474114/119688290-713c5900-be7a-11eb-9468-355be8701b66.png)
现在暂时没出现这个问题，具体为什么会断掉我也不清楚。

**Comment by lovezzzxxx** [comment]
wget就算超时断连应该也不会导致脚本停止运行才对，只能再观察看看了
另外启动没有使用nohup &的话是直接挂在screen里运行的吗？

**Comment by 9ikj** [comment]
我是挂在screen运行的

**Comment by LGKKY** [comment]
感觉很可能是内存不够或者什么原因被杀了 
我以前用screen挂程序的状态下不太稳定
