### ISSUE TITLE
reality的錄製方法(偵測不到開台)

### ISSUE THREAD

**Issue by alex12582001** [lovezzzxxx/liverecord#54]
看record_new.sh的內容，如果要錄製reality給的參數應該是對方的reality ID
`ubuntu@XXXX-u4:~$ sudo record/record_new.sh reality "雪菜 ゆな" -o "record_video/test"`
`[2021-05-28 04:35:16] metadata reality_雪菜 ゆな status 0`

但是都偵測不到開台
請問是我用法有錯嗎?

直播連結
[https://reality.app/viewer/9367972?adj_t=rxfdj4h_hwaht00&game=draw_multi](url)

**Comment by lovezzzxxx** [comment]
reality我这边挺久没有维护过了，应该是已经失效了，之后我看看能不能修好吧
