### ISSUE TITLE
nicoco nico的社区无法正确监测

### ISSUE THREAD

**Issue by yuvick** [lovezzzxxx/liverecord#55]
明明已经开播，status 永远为0，感觉是不是nicoco监测代码部分需要更新了，测试了好几个已经开播的status始终为0。

**Comment by lovezzzxxx** [comment]
reality我这边挺久没有维护过了，应该是已经失效了，之后我看看能不能修好吧

**Comment by yuvick** [comment]
好的，谢谢🙏
