### ISSUE TITLE
必须要一直连接着xshell吗，我关闭xshell后就停止了

### ISSUE THREAD

**Issue by fgb766211** [lovezzzxxx/liverecord#56]
请问xshell必须要一直连接着才能录制吗，我关闭xshell后录像就停止了

**Comment by SekiBetu** [comment]
后台运行：
```shell
nohup 你的指令 &
```

放入screen运行：
```shell
sudo apt install -y screen // 安装screen
screen -U -S 新的窗口名 // 创建新的窗口并进入，其他指令百度自己搜 linux screen指令
```

**Comment by fgb766211** [comment]
> 后台运行：
> 
> ```shell
> nohup 你的指令&
> ```
> 
> 无极屏中运行：
> 
> ```shell
> sudo apt install -y screen // 安装屏幕
> screen -U -S 新的窗口名 //创建新的窗口并进入，其他习惯百度自己搜linux screen 实践
> ```

感谢，我已经可以后台录制了！效果很棒，电脑再也不用挂着录播软件了
