### ISSUE TITLE
偵測youtube運行一個月後會突然不能錄影

### ISSUE THREAD

**Issue by alex12582001** [lovezzzxxx/liverecord#57]
>ubuntu@alex-u4:~$ sudo bash record/record_new.sh youtube "UCqm3BQLlJfvkTsX_hvm0UmA" -o "record_video/test"
>[2021-06-18 15:57:05] metadata main https://www.youtube.com/channel/UCqm3BQLlJfvkTsX_hvm0UmA/live status 1
>[2021-06-18 15:57:05] record start: PID=26278, PART_URL=UCqm3BQLlJfvkTsX_hvm0UmA, STREAM_ID=r-iTCjfBANQ, STREAM_URL=, FNAME=youtube_UCqm3BQLlJfvkTsX_hvm0UmA_20210618_155705_r-iTCjfBANQ.ts
>[2021-06-18 15:57:15] record already stopped
>[2021-06-18 15:57:15] record_video/test/youtube_UCqm3BQLlJfvkTsX_hvm0UmA_20210618_155705_r-iTCjfBANQ.ts file not exist remove log
>[2021-06-18 15:57:15] record end too early retry after 170 seconds

偵測youtube錄影穩定運行一個月左右會突然發生上述情況
能偵測到開台也會啟動錄影，但是啟動後10秒會直接停止，等待重啟後還是不斷重複相同狀況

曾經試過：
1. 換偵測不同的直播主情況並未改善
2. 上個月碰到我直接砍掉vps重建有用，一個月後(就是現在)還是碰到一樣的問題
3. 幫vps換public ip還是一樣

不知道是record_video有未知bug還是youtube會針對監控有防範機制?

**Comment by aTerminal** [comment]
youtube选项调用的是streamlink进行录制，根据分析发现youtube最近把私有的接口给改了，导致streamlink请求地址时会相应404。
这不是这个脚本的问题，将streamlink升级到2.2.0版本可以解决。

**Comment by aTerminal** [comment]
同时，在ffmpeg更新对YouTube的抓取机制前，youtubeffmpeg选项也是不可用的。
唯一的解决方法是把streamlink更新到2.2.0版本，然后使用youtube参数进行录制。

**Comment by SekiBetu** [comment]
- 可以尝试更新streamlink版本

```shell
pip3 install --upgrade git+https://github.com/streamlink/streamlink.git
```

- 或者手动更新 `youtube.py`

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/youtube.py

路径大概是这种，自行寻找 `/usr/local/lib/python3.8/site-packages/streamlink/plugins/`
找不到就 `find / -name youtube.py`

**Comment by alex12582001** [comment]
@aTerminal @SekiBetu 更新steamlink之後已解決，感謝!
