### ISSUE TITLE
录制文件名优化

### ISSUE THREAD

**Issue by imtipi** [lovezzzxxx/liverecord#72]
请问可以把录制文件名改成 平台(甚至让其可选和自定义)_频道名_直播标题_日期 吗
比如说 现在mea正在youtube直播歌回，直播标题为 【歌枠/アーカイブなし】今日はとってもアイドル！【神楽めあ】，那么现在的文件名字为 youtube_神楽めあ / KaguraMea_【歌枠/アーカイブなし】今日はとってもアイドル！【神楽めあ】_20211209.ts
感觉这样会更直观，但是我目前想不出来如何获取元数据（频道名与直播标题），也没写过shell，希望大佬们能想一想怎么写，谢谢

**Comment by imtipi** [comment]
潜在的解决方法（但只能用于youtube）
youtube-dl -f mp4 -o '%(id)s.%(ext)s' --print-json --no-warnings --skip-download "$url" >metadata
title=$(jq -r ".title" metadata)
uploader=$(jq -r ".uploader" metadata)
来自 https://stackoverflow.com/questions/47096751/get-youtube-video-title-while-video-downloading

**Comment by SekiBetu** [comment]
https://github.com/lovezzzxxx/liverecord/blob//record_new.sh#L164 自己改下这边就行了

**Comment by imtipi** [comment]
```
if [[ $TYPE == "youtube"* ]]; then
		STREAM_ID=$(echo $PAGE | grep -o '\"liveStreamabilityRenderer\":{\"videoId\":\".*\"' | head -n 1 | awk -F'"' '{print $6}')
   youtube-dl -f mp4 -o '%(id)s.%(ext)s' --print-json --no-warnings --skip-download "${FULL_URL}" >metadata
   title=$(jq -r ".title" metadata)
   uploader=$(jq -r ".uploader" metadata)
   rm -rf metadata
   FNAME="youtube_${uploader}_${title}_${STREAM_ID}.ts"
```
感谢，现在改好了
