### ISSUE TITLE
已编辑

### ISSUE THREAD

**Issue by zx3777** [lovezzzxxx/liverecord#77]

**Comment by SekiBetu** [comment]
streamlink参数不是用来录制的，是获取链接的

**Comment by zx3777** [comment]
> streamlink参数不是用来录制的，是获取链接的

脚本里不说能录制streamlink支持的网站吗？

**Comment by SekiBetu** [comment]
> > streamlink参数不是用来录制的，是获取链接的
> 
> 脚本里不说能录制streamlink支持的网站吗？

![image](https://user-images.githubusercontent.com/38283893/147905140-fea42e9f-a9d0-4bf1-8a42-8bbeb5a12c89.png)
![image](https://user-images.githubusercontent.com/38283893/147905148-428ff254-2c55-48ff-8c63-5f85cd51b612.png)

**Comment by SekiBetu** [comment]
作者想搞全局streamlink的，但是一直没时间搞

**Comment by zx3777** [comment]
https://github.com/limontec/Streamlink-Recorder 这个colab脚本可以录制afreecatv，可以参考一下。

**Comment by zx3777** [comment]
直接用streamlink是可以录制的，但是用脚本返回的网址就是错误的。
