### ISSUE TITLE
我推的主播换了油管域名，我跟着换指令之后发现还是录不上

### ISSUE THREAD

**Issue by HoshifuriKaoru** [lovezzzxxx/liverecord#86]
最近我推的主播换404域名了，录播机录不上了，我跟着把域名指令换掉之后发现还是录不上是什么原因？
我的指令是
nohup record/record_new.sh youtube "主播域名" -l 30 -o "record_video/主播" -l 30 -u baidupcs3 > log_mel_404.txt &
发现还是录不上
是我换的指令有啥问题么

**Comment by HoshifuriKaoru** [comment]
`此处可能需要较长时间，请耐心等待
Cloning into 'livedl'...
Username for 'https://github.com': `
准备用一键脚本重新装一下的，结果卡在了这里卡了几个小时

**Comment by HoshifuriKaoru** [comment]
此处可能需要较长时间，请耐心等待
Cloning into 'livedl'...
Username for 'https://github.com': 
Socket error Event: 32 Error: 10053.
Connection closing...Socket close.


挂了一晚上重装失败

**Comment by LGKKY** [comment]
一键脚本的livedl GitHub仓库 https://github.com/nnn-revo2012/livedl 已经失效 所以装不上

**Comment by HoshifuriKaoru** [comment]
> 一键脚本的livedl GitHub仓库 https://github.com/nnn-revo2012/livedl 已经失效 所以装不上

有人接手这个一件脚本么？不然以后想重新装都没法装了。
还好我删除之前留了快照，目前回滚快照还能录TC台（虽然经常失效和录制失败），404的话我推的主播的频道换域名了不知道为啥一直捕捉不到，新域名是主播名字罗马音，我怀疑这个域名是个假的域名

**Comment by LGKKY** [comment]
这脚本说实话年久失修 要搞的话最好都重新整整了


&nbsp;


kjfg_team
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月3日(星期一) 中午1:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lovezzzxxx/liverecord] 我推的主播换了油管域名，我跟着换指令之后发现还是录不上 (Issue #86)





  
一键脚本的livedl GitHub仓库 https://github.com/nnn-revo2012/livedl 已经失效 所以装不上
  
有人接手这个一件脚本么？不然以后想重新装都没法装了。
 还好我删除之前留了快照，目前回滚快照还能录TC台（虽然经常失效和录制失败），404的话我推的主播的频道换域名了不知道为啥一直捕捉不到，新域名是主播名字罗马音，我怀疑这个域名是个假的域名

**Comment by HoshifuriKaoru** [comment]
> 这脚本说实话年久失修 要搞的话最好都重新整整了 &nbsp; kjfg_team ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年7月3日(星期一) 中午1:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [lovezzzxxx/liverecord] 我推的主播换了油管域名，我跟着换指令之后发现还是录不上 (Issue #86) 一键脚本的livedl GitHub仓库 https://github.com/nnn-revo2012/livedl 已经失效 所以装不上 有人接手这个一件脚本么？不然以后想重新装都没法装了。 还好我删除之前留了快照，目前回滚快照还能录TC台（虽然经常失效和录制失败），404的话我推的主播的频道换域名了不知道为啥一直捕捉不到，新域名是主播名字罗马音，我怀疑这个域名是个假的域名 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

有人重整这个脚本的话请务必告诉我

**Comment by HoshifuriKaoru** [comment]
> 这脚本说实话年久失修 要搞的话最好都重新整整了 &nbsp; kjfg_team ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年7月3日(星期一) 中午1:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [lovezzzxxx/liverecord] 我推的主播换了油管域名，我跟着换指令之后发现还是录不上 (Issue #86) 一键脚本的livedl GitHub仓库 https://github.com/nnn-revo2012/livedl 已经失效 所以装不上 有人接手这个一件脚本么？不然以后想重新装都没法装了。 还好我删除之前留了快照，目前回滚快照还能录TC台（虽然经常失效和录制失败），404的话我推的主播的频道换域名了不知道为啥一直捕捉不到，新域名是主播名字罗马音，我怀疑这个域名是个假的域名 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

希望有人重整，有人重整的话请一定踹我一脚提醒我

**Comment by HoshifuriKaoru** [comment]
我好像找到原因了，油管是不是改过他们的域名啊，我看了下我的录播记录
[2023-07-05 00:00:18] metadata main https://www.youtube.com/channel/主播频道/live status 0
这个域名中间多了个/channel/
我现在进我主播直播间
https://www.youtube.com/主播频道/live
是这么个域名
中间的/channel/没了

**Comment by HoshifuriKaoru** [comment]
尝试修改
记事本打开record/record_new.sh
将下列内容中的/channel 删掉
`#转换完整链接
function getfullurl(){
	local TYPE=$1
	local PART_URL=$2
	[[ $TYPE == "youtube"* ]] && echo "https://www.youtube.com/channel/${PART_URL}/live"`
上传 重新运行脚本
现在正在测试看行不行

**Comment by HoshifuriKaoru** [comment]
> 尝试修改 记事本打开record/record_new.sh 将下列内容中的/channel 删掉 `#转换完整链接 function getfullurl(){ local TYPE=$1 local PART_URL=$2 [[ $TYPE == "youtube"* ]] && echo "https://www.youtube.com/channel/${PART_URL}/live"` 上传 重新运行脚本 现在正在测试看行不行

确信该方法可行 已解决
